model:
  name: "VAE"
  image_size: 128
  in_channels: 3
  latent_dim: 128
  hidden_dim: [32, 64, 128, 256, 512]

dataset:
  type: "CUB200"
  path: "data"
  img_size: 128
  batch_size: 36
  center_crop_scale: 1.2

optimizer:
  adam_beta1: 0.9
  adam_beta2: 0.999
  learning_rate: 0.005
  weight_decay: 0.0
  eps: 0.0000001

scheduler:
  gamma: 0.95

trainer:
  max_epoch: 50
  multigpu: False

inferencer:
  sample_num: 36

stats:
  stats_dir: "stats"
  stats_folder: "VAE-CUB200"