model:
  name: 'vae'
  image_size: 64
  in_channels: 3
  latent_dim: 128
  hidden_dim: [32, 64, 128, 256, 512]

experiment:
  data_path: "data"
  img_size: 64
  batch_size: 144
  sample_num: 144
  learning_rate: 0.005
  weight_decay: 0.0
  eps: 0.000001
  scheduler_gamma: 0.95
  center_crop: 148

trainer:
  gpus: 1
  max_epochs: 50

logger:
  save_dir: "logs"
  name: "vae"